let name = 'John shrimp taco VI';
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
console.log(name);
